### ISSUE TITLE
slack join link is not active anymore

### ISSUE THREAD

**Issue by mathematikoi** [json-schema-org/blog#34]
click on "join slack" in the navbar

**Comment by Relequestual** [comment]
Hey @mathematikoi, sorry about that! I'll update it, but for now, here you go! https://join.slack.com/t/json-schema/shared_invite/zt-1ywpdj4yd-bXiBLjYEbKWUjzon0qiY9Q

**Comment by Relequestual** [comment]
Thanks for raising the issue, much appreciated!
